### ISSUE TITLE
Trying to call `isSubclassOf` method of `null`

### ISSUE THREAD

**Issue by ncrypthic** [SymfonyId/AdminBundle#14]
Hi,

During installation on windows, encountered error with message `trying to call method 'isSubclassOf' of null` on [SiabRouteLoader](https://github.com/SymfonyId/AdminBundle/blob/master/Route/SiabRouteLoader.php#L62) class.

**Comment by ihsanudin** [comment]
@ncrypthic : fix by this commit

`https://github.com/SymfonyId/AdminBundle/commit/7e96f3c205c19563fa4d079917d0a709c874f057`

Thanks for reporting the bug
