### ISSUE TITLE
Nice-To-Have Features: Master Detail Form

### ISSUE THREAD

**Issue by pitraadytia** [SymfonyId/AdminBundle#25]
i thought out of the box master detail form seems nice to have features

![masterdetail](https://cloud.githubusercontent.com/assets/8655316/14653153/dcdb2c18-06a1-11e6-902f-1f4db2e9c8b6.jpg)

**Comment by ihsanudin** [comment]
@pitraadytia : aku masih belum nemu konsepnya untuk ini

**Comment by ucay** [comment]
kalau render CollectionType bisa ga Om?
harusnya klo itu bisa, bikin detail itu gampang, hehe :dancer:

**Comment by ihsanudin** [comment]
Aku malah kepikirannya, kita bikin flat table trus formnya dirender dibagian atas table. Nanti di post via ajax

**Comment by pitraadytia** [comment]
kalo pakek fitur macros nya twig gimana. jadi bikin macros yang ngerender 1 entity , terus nanti di looping. tamba2 nya tinggal panggil macros itu.

**Comment by ihsanudin** [comment]
@pitraadytia : dicoba dulu pak :dancer:
