### ISSUE TITLE
Twig Listener Register Global Variable Deprecated

### ISSUE THREAD

**Issue by ucay** [SymfonyId/AdminBundle#37]
Testing di skeleton ada `deprecated notices` ketika pertama kali install.
```
Registering global variable "locale" at runtime or when the extensions have already been initialized is deprecated since version 1.21: 1x
    1x in DefaultControllerTest::testIndex from Tests\AppBundle\Controller
```
ini merujuk ke  [EventListener/TwigVariableListener.php](https://github.com/SymfonyId/AdminBundle/blob/master/EventListener/TwigVariableListener.php#L87)

Sepertinya sebelum `addGlobal()` dicek dulu apakah variable global tersebut sudah ada. Kalau sudah ada, ganti value nya. Kalau belum baru `addGlobal()`

**Comment by ihsanudin** [comment]
@ucay : ok ntar coba dicek dulu satu2 kalau gitu om

**Comment by ihsanudin** [comment]
Fixed by @010df754c00d6344a539f85b5919a00b62c50b85
