### ISSUE TITLE
datetime popup js error timeformat is not function di chrome console

### ISSUE THREAD

**Issue by pitraadytia** [SymfonyId/AdminBundle#38]
error js dan datetime popup tidak tampil.

![screen shot 2016-09-27 at 11 14 58](https://cloud.githubusercontent.com/assets/8655316/18859929/cb2d91f2-84a2-11e6-91cb-566358cc47cb.png)

penyebab di new.html. twig

```
{%- block date_picker -%}
    {{- use_date_picker -}}
{%- endblock -%}

```

solusi  sementara

```
{%- block date_picker -%}
    {% if date_picker is defined %}
        {{- use_date_picker -}}
    {% endif %}
{%- endblock -%}
```

**Comment by ad3n** [comment]
Fix ya pak
