### ISSUE TITLE
Filter untuk date tidak berfungsi

### ISSUE THREAD

**Issue by pitraadytia** [SymfonyId/AdminBundle#39]
Filter di grid untuk date tidak berfungsi 

contoh  : 

entity : 

```
    /**
     * @ORM\Column(type="date")
     * @Filter()
     */
    protected $mulaiCuti;
```

Controller : 

`filter=@Siab\Filter({"namaPelanggan","workflow","mulaiCuti"})`

Query yang di hasilkan  

`SELECT DISTINCT p0_.id AS id_0, p0_.id AS id_1 FROM permintaan_cuti p0_ WHERE (p0_.mulai_cuti = '01-09-2016' OR p0_.workflow LIKE '%01-09-2016%' OR p0_.nama_pelanggan LIKE '%01-09-2016%') ORDER BY p0_.id DESC LIMIT 17 OFFSET 0`

seharusnya apa tidak mulai_cuti = '2016-09-01' ikutin format database

**Comment by ad3n** [comment]
Fix pak sudah diganti jadi Y-m-d untuk querynya
